name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  test:
    name: "Test on Node.js ${{ matrix.node }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [24]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x
          run_install: true

      - name: Test
        run: pnpm test

  lint:
    runs-on: ubuntu-latest
    name: Lint source code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x
          run_install: true

      - name: Lint
        run: pnpm lint
